create or replace
FUNCTION BIB_NBKI_GET_REQ RETURN VARCHAR2 AS  
  OUT_ST VARCHAR2(32000);
/* нбки */
BEGIN
    OUT_ST := IBS.Z$BIB_SCOR_REQ_LIB.SendOneFIFO;
return OUT_ST;  
END BIB_NBKI_GET_REQ;

create or replace
FUNCTION BIB_NBKI_SET_RES(NUM_REQ VARCHAR2, SCOR_BALL VARCHAR2) RETURN VARCHAR2 AS  
  OUT_ST VARCHAR2(10);
/* нбки */
BEGIN
    OUT_ST := IBS.Z$BIB_SCOR_REQ_LIB.GetScoringOne(NUM_REQ, SCOR_BALL);
return OUT_ST;  
END BIB_NBKI_SET_RES;

create or replace
FUNCTION BIB_NBKI_SET_RES_ERR(NUM_REQ VARCHAR2, TEXT_ERR VARCHAR2) RETURN VARCHAR2 AS  
  OUT_ST VARCHAR2(10);
/* нбки */
BEGIN
    OUT_ST := IBS.Z$BIB_SCOR_REQ_LIB.GetErrorText(NUM_REQ, TEXT_ERR);
return OUT_ST;  
END BIB_NBKI_SET_RES_ERR;
